// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmm1c_EIL48wIiO0-S06TX2RlUXPnK9ko',
    appId: '1:246507010043:web:1980dddb0e1a660d9abd5e',
    messagingSenderId: '246507010043',
    projectId: 'project-database-3265e',
    authDomain: 'project-database-3265e.firebaseapp.com',
    storageBucket: 'project-database-3265e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxF0XRi3sd8_2YfTS8bt34HRVcpmc7LV4',
    appId: '1:246507010043:android:e4760d37db145a619abd5e',
    messagingSenderId: '246507010043',
    projectId: 'project-database-3265e',
    storageBucket: 'project-database-3265e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX5C3en17L7iGI6goqFROjFLklBEAjQ6Q',
    appId: '1:246507010043:ios:1580cd1731b8add29abd5e',
    messagingSenderId: '246507010043',
    projectId: 'project-database-3265e',
    storageBucket: 'project-database-3265e.firebasestorage.app',
    iosBundleId: 'com.example.cadenceProject',
  );
}
